# Primary Brewfile for tooling
tap "common-fate/granted", trusted: { formula: "granted" }
tap "derailed/k9s", trusted: { formula: "k9s" }
tap "grafana/grafana", trusted: { formula: "gcx" }
tap "hashicorp/tap", trusted: { formula: "vagrat" }
tap "int128/kubelogin", trusted: { formula: "kubelogin" }
brew "argocd"
brew "autoconf"
brew "bat"
brew "chart-testing"
brew "cloudflared"
brew "cmake"
brew "curl"
brew "difftastic"
brew "direnv"
brew "eza"
brew "fzf"
brew "gawk"
brew "gcx"
brew "gh"
brew "git"
brew "gitlab-ci-local"
brew "glab"
brew "glow"
brew "gnupg"
brew "granted"
brew "graphviz"
brew "htop"
brew "jfrog-cli"
brew "jq"
brew "k6"
brew "k9s"
brew "kcat"
brew "kubectx"
brew "kubelogin"
brew "mkcert"
brew "mtr"
brew "ncurses"
brew "nmap"
brew "nvim"
brew "pyenv"
brew "ripgrep"
brew "speedtest-cli"
brew "rectangle"
brew "sqlite"
brew "stow"
brew "tmux"
brew "watch"
brew "wget"
brew "xz"
brew "ykman"
brew "yq"
brew "zstd"
cask "1password-cli"
cask "bruno"
cask "gpg-suite"
cask "hashicorp/tap/hashicorp-vagrant", trusted: true
cask "qlmarkdown"
cask "wizcli"
# Global NPM tooling
npm "@devcontainers/cli"
npm "corepack"
npm "k6"
# VSCode plugins
vscode "dracula-theme.theme-dracula"
vscode "hashicorp.terraform"
vscode "k6.k6"
