# frozen_string_literal: true

source "https://rubygems.org"

gem 'net-ssh','~> 3.0'
gem "concurrent-ruby", "~> 1.3"
gem "kitchen-ansible", "~> 0.58.0"
gem "kitchen-docker", "~> 3.4"
gem "kitchen-verifier-serverspec", "~> 0.7.2"
gem "serverspec", "~> 2.43"
gem "test-kitchen", "~> 4.1"

group :test do
  gem "bundler", "~> 4.0"
  gem "minitest", "~> 6.0"
  gem "rake", ["~> 13.4", ">= 12.3.3"]
  gem "simplecov", "~> 1"
end
